### ISSUE TITLE
`attrs.type_("search")` rendering as `type_="search"`

### ISSUE THREAD

**Issue by lpil** [nakaibuild/nakai#13]
Hello!

I've found a bug, introduced in v0.6. Escaped attribute names render using the escaped name in the HTML.

https://diff.hex.pm/diff/nakai/0.5.0..0.6.0#72857028--186

Thanks,
Louis

**Comment by aslilac** [comment]
Thanks! Should be fixed in v0.6.2

**Comment by aslilac** [comment]
also hexdiff is super cool, never knew about that!
