### ISSUE TITLE
Render non-root

### ISSUE THREAD

**Issue by NthTensor** [nakaibuild/nakai#17]
Would it be possible to expose the ability to render arbitrary HTML nodes rather than full documents? Seems like this feature is hidden in `/internal/render.gleam` right now.

Use-Case: Running in a browser sometimes you need to plug stuff into `innerHTML`.

**Comment by aslilac** [comment]
thanks for the nerd snipe :^) been meaning to get around to this

**Comment by NthTensor** [comment]
Awesome! Thanks so much, and so quickly too!
