### ISSUE TITLE
Thoughts on interactivity

### ISSUE THREAD

**Issue by aslilac** [nakaibuild/nakai#20]
- If the server decides an initial state, how do we serialize this and deliver it to the client?
  - Do we just not?
  - Do we assume that client will do its own data fetching? Potentially really wasteful
  - It's probably too important to discard, the client should really be aware of what its state is so it doesn't have to refetch.
- How do we know what our `view` function is on the client?

```gleam
pub fn view(model) {
  html.p_text([], "The count is " <> int.to_string(model.count))
}
```

```html
<html>
<body>
<p>The count is 0</p>
<script src="./app.js"></script>
<script type="text/x-nakai-serialized-state">
{"count": 0}
</script>
</body>
</html>
```

**Comment by aslilac** [comment]
```gleam
pub type Document {
  Document(
    doctype: Option(String),
    html_attrs: StringBuilder,
    body_attrs: StringBuilder,
    head: StringBuilder,
    body: DocumentContent,
    scripts: List(String),
  )
}

pub type DocumentUpdate(a) {
  DocumentUpdate(title: String, body: List(html.Node(a)))
}

pub type DocumentContent(model, a) {
  DocumentContent(fn(model) -> DocumentUpdate(a))
}
```

**Comment by aslilac** [comment]
```gleam
pub type Document {
  Document(
    doctype: Option(String),
    html_attrs: StringBuilder,
    body_attrs: StringBuilder,
    head: StringBuilder,
    body: DocumentContent,
    scripts: List(String),
  )
}

pub type DocumentUpdate(a) {
  DocumentUpdate(title: String, body: List(html.Node(a)))
}

pub type DocumentContent(model, a) {
  DocumentContent(fn(model) -> DocumentUpdate(a))
}
```

**Comment by Rhal95** [comment]
I'm not sure if Nakai needs to solve this. You can (and probably should) just go the HATEOAS route and just put all of the state into the html. Updates can be done using htmx, AJAX or a plain full page reload.

All "hidden" state that is too important to throw away but is needed on the next request can be encoded just like that.
```
html.input([
  attrs.type_("hidden"), 
  attrs.name("my_secret_data"), 
  attrs.value("I like gleam")
])
```

No matter how you implement interactivity for your application, it is not the responsibility of the html rendering itself.

**Comment by aslilac** [comment]
yeah, I created this issue before lustre existed, so I'm not really that invested in making interactivity nakai's problem anymore. I think embracing htmx would be an interesting direction forward.

**Comment by aslilac** [comment]
0.10 (1.0-rc, sort of) has removed all of the experimental stuff, and no longer provides any sort of interactivity primitives. anyone looking for those would likely be well served by simple inline scripts, something like htmx, or just using lustre instead.
