### ISSUE TITLE
Add attributes to Script

### ISSUE THREAD

**Issue by schtauffen** [nakaibuild/nakai#22]
It is unclear how you reference external scripts since the included `Script` only accepts script: String;

In addition to allowing `src` attr, it should also allow async, and other script attributes.

**Comment by aslilac** [comment]
`html.Script` is kind of a weird experimental thing I haven't fleshed out. what you want is `html.Element("script", attrs, [])` :)

**Comment by aslilac** [comment]
This has been changed in 0.11. `html.Script` is now defined as `Script(attrs: List(Attr), content: String)`.
