### ISSUE TITLE
Figure out a good story for CSS and static assets

### ISSUE THREAD

**Issue by aslilac** [nakaibuild/nakai#4]

**Comment by mikeyjones** [comment]
For CSS could the API be something like:

```gleam

let css_rules = [
   css.rule(".class-item", [
      css.color(colors.Pink),
      css.font_family([fonts.cursive(), "Comic Sans MS" ])
      css.font_size(size.em(2.0))
   ]
]

````

Would the goal be that we can render the CSS with the view (i.e. add style tags in the rendered out view)? I think it would be good if we can render the CSS separate to the view, so some apps could output a css file, what are your thoughts?

**Comment by aslilac** [comment]
I’m actually thinking something more in line with CSS modules or styled-components. I want people to he able to copy and paste CSS without lots of reformatting.

We have to keep in mind that CSS is more than just rules. It’s also media queries, and font definitions, etc.

**Comment by aslilac** [comment]
I'm now thinking that this isn't really Nakai's job. something for another library to solve, perhaps!
