### ISSUE TITLE
Areas to help out in? Looking to contribute. 

### ISSUE THREAD

**Issue by ajstrand** [nakaibuild/nakai#6]
Hi @aslilac I've been on the gleam discord for a little while and noticed your project. 

I'm interested in contributing, but I'm not sure where to start. 

Do you have any ideas in mind?

**Comment by ajstrand** [comment]
One idea I just thought of is how to let a user embed/use JS components for stuff that Nakai doesn't support yet. 

Im thinking of sort of flag in the compiler that can tell the code to ignore certain files. 

You could tell the user that they have to do their own transpiling(with babel/esbuild) etc. 

That way you don't have to write as much code to support something like this.

**Comment by aslilac** [comment]
I'm open to discussion, but I don't think I wanna encourage embedding JavaScript. I'd be much more in favor of finding ways for people to express things in Gleam. I'm not really afraid of "writing so much code" as long as the developers downstream get a good experience out of it. (and a lot of things can just be done with code generation, which we're already doing anyway)

**Comment by ajstrand** [comment]
Hey, I agree with what you mentioned, embedding JavaScript would just be an extra  maintenance burden and like you said it shifts people away from writing their app code in gleam. 

I saw you had some ideas about how to do CSS styles, is that an area you want to focus on right now? I’d be happy to help with effort if that’s where you think it’s good to spend time.

**Comment by aslilac** [comment]
Yeah, I definitely wanna have a better CSS story. I don't have a very solid idea of what it should look like yet though.

**Comment by aslilac** [comment]
Honestly, the way I've been approaching development so far is just trying to build little things using Nakai, looking for moments where I find myself saying "I wish I could..." and then figuring out how to make those things possible. Might be a good way to find some small contributions to start with. :)
