### ISSUE TITLE
Html tag doesn't have a lang attribute

### ISSUE THREAD

**Issue by ajstrand** [nakaibuild/nakai#7]
The html generated by Nakai in a sample project doesn't have a lang attribute. 

Looking through the code, it looks like there's some extra code that needs to be written to support lang attributes. 

I think I'm close to having something working and I'll try to put up a PR later this week.

**Comment by aslilac** [comment]
Yeah, document attributes are important to support. `render_root` should probably just take a `List(Attr(a))`, and then propagate that up to the public render functions as well.

**Comment by aslilac** [comment]
added support for this in v0.3.5 via `nakai.{render_with_document_attrs}`
