### ISSUE TITLE
A function to render to a string builder

### ISSUE THREAD

**Issue by lpil** [nakaibuild/nakai#8]
Hello!

Thanks for the library 💜 

Most the time I think Nakai HTML will be written to a socket or a file, in which case converting to a string is wasted work. Could we have a function that does this? It might even be better to have `render` return a builder and have another `render_to_string` function.

Thanks,
Louis

**Comment by aslilac** [comment]
I think at that point I'd rather just recommend that people use `string_builder.to_string`, but having `render` return a `StringBuilder` is probably fine, since that's what it uses internally anyway
