### ISSUE TITLE
More flexible link element

### ISSUE THREAD

**Issue by lpil** [nakaibuild/nakai#9]
Hello!

I need to be able to set other attribute on the `link` element such as `type` and `crossorigin`. How might I do this?

Thanks,
Louis

**Comment by aslilac** [comment]
`html.link` takes a `List(Attr(a))`; you should be able to set any attributes you want.

```gleam
import nakai/html

html.head([
  html.link([attrs.rel("preload"), attrs.type(...), attrs.crossorigin(), ...])
])
```

The functions in `nakai/head` (which I think is the `link` that you're referring to) are a little more "opinionated". I'm not sure they're the right approach, but I think one day when we have default arguments it'll be able to be improved a little.

**Comment by lpil** [comment]
Ah, thank you! That's fab. I thought there was only the ones in the `head` module
